// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /iphc-data/safe1/cms/gcoulon/CMSSW_15_0_13_patch1/src/TupleAnalysis/macros/./HSCPSelector.h;
#pragma link C++ defined_in "/iphc-data/safe1/cms/gcoulon/CMSSW_15_0_13_patch1/src/TupleAnalysis/macros/./HSCPSelector.C";

#endif
